### ISSUE TITLE
link previewer doesn't preview .jpeg

### ISSUE THREAD

**Issue by zzzw** [mrchess/stations-issues#21]
images ended in .jpeg are ignored by the link previewer thing.

reproduce this by posting a jpeg in chat, like this one: http://i.imgur.com/bMqmuRg.jpeg

**Comment by zzzw** [comment]
ATM 11:32 AM
when you tell cheese to fix .jpeg tell him to do .JPG as well 

uwu 11:32 AM
tell him to do .tiff as well
and .svg

**Comment by mrchess** [comment]
how do you do .tiff? you can embed that?

**Comment by mrchess** [comment]
i dont think tff and svg can be supported. you need plugins to view them? tiff at least since it uses <object> tag?

**Comment by mrchess** [comment]
i consider svg and tiff separate issue.

if you give me some example code that tells me how to correctly handle if svg and tiff cannot load/requires a pluging, i can add it (just like how image has `onerror`). does svg/tiff have `onpluginrequired`? etc

**Comment by zzzw** [comment]
they were joking I think
