### ISSUE TITLE
give people a way to monitor when they are @mention

### ISSUE THREAD

**Issue by pclget** [mrchess/stations-issues#29]
some kind of notification?

**Comment by pclget** [comment]
random, from a quora answer on why irc is still used:

"I primarily use it to speak with friends who refuse to join a social network. It is a decent alternative for users who are not comfortable putting all of their personal information out on the web, while still being able to communicate efficiently with friends/colleagues/coworkers.

It's also nice to have a group chatroom where you aren't bombarded with notifications unless you are mentioned personally (something I find slightly annoying about group Facebook chats or group text messages)."

**Comment by pclget** [comment]
when we hit mobile, perhaps only 1:1 & @mention should create notifications

**Comment by mrchess** [comment]
added a new indicator on sidebar, blue badge, that tells when ur mentioned. sufficient?
