### ISSUE TITLE
chat bug - user sending messages twice on each input

### ISSUE THREAD

**Issue by pclget** [mrchess/stations-issues#43]
Aquamarine 9:29 PM  
do any of you guys listen to F.Cuz?
do any of you guys listen to F.Cuz?
swaeg 9:29 PM  
a little
The poll Girl or Guy has ended. The results are:
Girl , 5 votes
Guy , 4 votes
crackhyeyeon 9:29 PM  
never heard
[MV] 매드클라운(Mad Clown) _ 화(Fire... was propped +1
Guest2644 9:29 PM  
yes
Aquamarine 9:29 PM  
totes check them out :3
totes check them out :3
why is this
why is this
Aquamarine 9:30 PM  

> _> sorry it keeps sending twice
> _> sorry it keeps sending twice

**Comment by pclget** [comment]
solved by relogging

weird

**Comment by mrchess** [comment]
fixed in 768dacc
