### ISSUE TITLE
bug - button issues during mass playlist manipulation

### ISSUE THREAD

**Issue by pclget** [mrchess/stations-issues#50]
tracking here

fix the buttons on the vids
pls
civ 5:18 PM  
wat buttons
Keldaneh 5:18 PM  
"delete" "bump"
5:18 PM they get weird when you try to mass remove
civ 5:18 PM  
not working?
Keldaneh 5:18 PM  
or mass bump
they work
atleast for me
it doesn't work to remove the vid that takes the spot of the last removed vid
for like some seconds

**Comment by mrchess** [comment]
i think i fixed this
